plugins {
    // this is necessary to avoid the plugins to be loaded multiple times in each subproject's classloader
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.multiplatform.library) apply false
    alias(libs.plugins.compose.multiplatform) apply false
    alias(libs.plugins.kotlin.multiplatform) apply false
    alias(libs.plugins.kotlin.compose.compiler) apply false
    alias(libs.plugins.kotlin.serialization) apply false
    alias(libs.plugins.ksp) apply false
}

tasks.register("generateAppVersionConfig") {
    group = "versioning"
    description = "Generates Version config files from libs.versions.toml"

    val versionCode = libs.versions.app.version.code.get()
    val versionName = libs.versions.app.version.name.get()
    
    val iosOutputFile = file("iosApp/Configuration/Version.xcconfig")
    val commonOutputFile = file("shared/src/commonMain/kotlin/se/supernovait/doobypro/AppConfig.kt")

    inputs.property("versionCode", versionCode)
    inputs.property("versionName", versionName)
    outputs.files(iosOutputFile, commonOutputFile)
    
    doLast {
        // Generate iOS Config
        iosOutputFile.writeText(
            """
            // Generated by Gradle generateAppVersionConfig task
            CURRENT_PROJECT_VERSION = $versionCode
            MARKETING_VERSION = $versionName
            """.trimIndent() + "\n"
        )
        
        // Generate Common Kotlin Config
        commonOutputFile.parentFile.mkdirs()
        commonOutputFile.writeText(
            """
            package se.supernovait.doobypro

            // Generated by Gradle generateAppVersionConfig task
            object AppConfig {
                const val VERSION_CODE = $versionCode
                const val VERSION_NAME = "$versionName"
            }
            """.trimIndent() + "\n"
        )
    }
}

// Ensure the version config is generated before any source processing in subprojects
val generateVersionTask = tasks.named("generateAppVersionConfig")

subprojects {
    tasks.configureEach {
        if (name.contains("Kotlin") || name.contains("ksp") || name.contains("Metadata")) {
            dependsOn(generateVersionTask)
        }
    }
}